// Level++, a levelset library in C++
//
// Author   : Chris H. Rycroft (LBL / UC Berkeley)
// Email    : chr@alum.mit.edu
// Date     : January 20th 2009

// This file is generated by the leonardo.pl script and is not intended to be
// edited by hand.

static const int smb[32];
static const int smc[32];
static const int smd[32];
