# Compiler and compilation flags
cc=gcc-9
cxx=g++-9 -fopenmp
cflags=-Wall -ansi -pedantic -O3

# MPI compiler
mpicxx=mpicxx -Wno-long-long

# Flags for linking to PNG library
png_iflags=-DHAS_PNG -I/opt/local/include
png_lflags=-L/opt/local/lib -lpng

# Flags for FFTW library
fftw_iflags=-I/opt/local/include
fftw_lflags=-L/opt/local/lib -lfftw3

# LAPACK flags for linear algebra
lp_lflags=-framework Accelerate
