helmholtz.o: helmholtz.cc helmholtz.hh tgmg.hh tgmg_config.hh \
 tgmg_predict.hh tgmg.cc
grating.o: grating.cc grating.hh tgmg.hh tgmg_config.hh tgmg_predict.hh \
 tgmg.cc
poisson_fd.o: poisson_fd.cc poisson_fd.hh tgmg.hh tgmg_config.hh \
 tgmg_predict.hh tgmg.cc
poisson_fem.o: poisson_fem.cc tgmg.hh tgmg_config.hh tgmg_predict.hh \
 poisson_fem.hh tgmg.cc tgmg_debug.cc
vpoiss_fem.o: vpoiss_fem.cc tgmg.hh tgmg_config.hh tgmg_predict.hh \
 vpoiss_fem.hh tgmg.cc tgmg_debug.cc
poisson_1d.o: poisson_1d.cc poisson_1d.hh conj_grad.hh
conj_grad.o: conj_grad.cc conj_grad.hh
